Remove setup.cfg as a manifest
This file will always be accompanied by a `setup.py` or `pyproject.toml`

`setuptools` [documents][1] how to use `setup.cfg` without `setup.py`,
but doing that requires `pyproject.toml`. Indeed, `pip-compile` fails
when it is run on a project that only has `setup.cfg`:

```
build.BuildException: Source <path> does not appear to be a Python project: no pyproject.toml or setup.py
```

[1]: https://setuptools.pypa.io/en/latest/setuptools.html#setup-cfg-only-projects